"""Camera construction and projection helpers."""

from __future__ import annotations

from _pipeline import (
    CAMERA_RADIUS,
    CAMERAS,
    FOCAL_LENGTH_MM,
    PREVIEW_HEIGHT,
    PREVIEW_WIDTH,
    SENSOR_HEIGHT_MM,
    SENSOR_WIDTH_MM,
    VIEW_CAMERA_SOURCE,
    VIEW_ORDER,
    VIEWS,
    Camera,
    build_camera_from_direction,
    build_multiview_cameras,
    camera_for,
    camera_from_position,
    project,
    project_world_to_pixels,
    rotate_toward,
    to_view_coords,
    trajectory_camera,
    world_to_camera,
)

__all__ = [
    "Camera",
    "CAMERA_RADIUS",
    "FOCAL_LENGTH_MM",
    "SENSOR_WIDTH_MM",
    "SENSOR_HEIGHT_MM",
    "PREVIEW_WIDTH",
    "PREVIEW_HEIGHT",
    "VIEW_ORDER",
    "VIEW_CAMERA_SOURCE",
    "CAMERAS",
    "VIEWS",
    "build_camera_from_direction",
    "build_multiview_cameras",
    "rotate_toward",
    "camera_for",
    "camera_from_position",
    "trajectory_camera",
    "project",
    "world_to_camera",
    "project_world_to_pixels",
    "to_view_coords",
]
